#!/bin/bash
# =============================================================================
# setup-env.sh
#
# Interactive setup script for Ando.Server environment variables.
# This script generates required secrets and creates a .env file.
#
# Usage:
#   chmod +x setup-env.sh
#   ./setup-env.sh
#
# The script will:
#   1. Generate encryption key
#   2. Generate SQL Server password
#   3. Prompt for GitHub App credentials
#   4. Create .env file with all configuration
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                    Ando.Server Environment Setup                   ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Output file
ENV_FILE="${1:-.env}"

if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}Warning: $ENV_FILE already exists.${NC}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 1
    fi
fi

echo -e "${GREEN}Generating secrets...${NC}"

# Generate encryption key (32 bytes, base64)
ENCRYPTION_KEY=$(openssl rand -base64 32)
echo "  - Encryption key: generated"

# Generate SQL Server password (24 chars + special char)
SA_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)
SA_PASSWORD="${SA_PASSWORD}!"
echo "  - SQL Server password: generated"

# Generate webhook secret
WEBHOOK_SECRET=$(openssl rand -hex 32)
echo "  - Webhook secret: generated"

echo ""
echo -e "${BLUE}GitHub App Configuration${NC}"
echo "Create a GitHub App at: https://github.com/settings/apps/new"
echo ""

read -p "GitHub App ID (numeric): " GITHUB_APP_ID
read -p "GitHub Client ID (starts with Iv1.): " GITHUB_CLIENT_ID
read -sp "GitHub Client Secret: " GITHUB_CLIENT_SECRET
echo ""

echo ""
echo -e "${BLUE}Optional Configuration${NC}"
echo ""

read -p "Resend API Key (leave empty to disable email): " RESEND_API_KEY
read -p "Email from address (e.g., builds@yourdomain.com): " RESEND_FROM_ADDRESS

if [ -z "$RESEND_FROM_ADDRESS" ]; then
    RESEND_FROM_ADDRESS="builds@localhost"
fi

echo ""
echo -e "${BLUE}Storage Paths${NC}"
echo "Default paths are for TrueNAS. Adjust if needed."
echo ""

read -p "Data directory [/mnt/tank/ando]: " DATA_DIR
DATA_DIR="${DATA_DIR:-/mnt/tank/ando}"

echo ""
echo -e "${GREEN}Creating $ENV_FILE...${NC}"

cat > "$ENV_FILE" << EOF
# =============================================================================
# Ando.Server Environment Configuration
# Generated by setup-env.sh on $(date)
# =============================================================================

# -----------------------------------------------------------------------------
# Environment
# -----------------------------------------------------------------------------
ASPNETCORE_ENVIRONMENT=Production

# -----------------------------------------------------------------------------
# Database
# -----------------------------------------------------------------------------
SA_PASSWORD=${SA_PASSWORD}
CONNECTION_STRING=Server=sqlserver;Database=AndoServer;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;Encrypt=true

# -----------------------------------------------------------------------------
# Encryption (AES-256)
# IMPORTANT: Keep this key safe. Losing it means losing access to encrypted data.
# -----------------------------------------------------------------------------
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# -----------------------------------------------------------------------------
# GitHub App
# Configure at: https://github.com/settings/apps
# -----------------------------------------------------------------------------
GITHUB_APP_ID=${GITHUB_APP_ID}
GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
GITHUB_WEBHOOK_SECRET=${WEBHOOK_SECRET}

# -----------------------------------------------------------------------------
# Email Notifications (Resend)
# Sign up at: https://resend.com
# -----------------------------------------------------------------------------
RESEND_API_KEY=${RESEND_API_KEY}
RESEND_FROM_ADDRESS=${RESEND_FROM_ADDRESS}
RESEND_FROM_NAME=Ando CI

# -----------------------------------------------------------------------------
# Build Configuration
# -----------------------------------------------------------------------------
BUILD_TIMEOUT_MINUTES=15
BUILD_MAX_TIMEOUT_MINUTES=60
BUILD_WORKER_COUNT=2
BUILD_DOCKER_IMAGE=mcr.microsoft.com/dotnet/sdk:9.0-alpine

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------
ARTIFACT_RETENTION_DAYS=30
LOG_RETENTION_DAYS=90
DATA_DIR=${DATA_DIR}

# -----------------------------------------------------------------------------
# Test Environment (only used when ASPNETCORE_ENVIRONMENT=Testing)
# -----------------------------------------------------------------------------
TEST_API_KEY=$(openssl rand -hex 16)
EOF

chmod 600 "$ENV_FILE"

echo ""
echo -e "${GREEN}✓ Environment file created: $ENV_FILE${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo ""
echo "1. Copy your GitHub App private key to: ${DATA_DIR}/config/github-app.pem"
echo ""
echo "2. Update your GitHub App webhook URL to:"
echo "   https://your-domain.com/webhooks/github"
echo ""
echo "3. Set the webhook secret in GitHub App settings to:"
echo -e "   ${BLUE}${WEBHOOK_SECRET}${NC}"
echo ""
echo "4. Copy the .env file and docker-compose.yml to ${DATA_DIR}/config/"
echo ""
echo "5. Start the services:"
echo "   cd ${DATA_DIR}/config"
echo "   docker compose up -d"
echo ""
echo -e "${RED}IMPORTANT: Keep this .env file secure. It contains sensitive credentials.${NC}"
echo ""
